"""empty message

Revision ID: 1e835db52c64
Revises: 3f64fad8f381
Create Date: 2023-03-18 19:51:41.467921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e835db52c64'
down_revision = '3f64fad8f381'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=40), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
