"""empty message

Revision ID: db7e4e5ba535
Revises: af3ec20c9bb7
Create Date: 2023-03-16 14:28:34.148574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db7e4e5ba535'
down_revision = 'af3ec20c9bb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade', sa.String(length=1), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.drop_column('grade')

    # ### end Alembic commands ###
